# Generated by Django 3.2 on 2021-04-18 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Create at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Create at')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Name of scraper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Create at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Create at')),
                ('type', models.CharField(db_index=True, max_length=32, verbose_name='Type of info')),
                ('meta_id', models.CharField(db_index=True, max_length=64, null=True, verbose_name='Some freely chooseable ID')),
                ('data', models.JSONField(null=True, verbose_name='Any meta information')),
                ('scraper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_scraper.scrapermodel', verbose_name='Scraper that retrieved the image that is meta-infoed')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Create at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Create at')),
                ('filename', models.CharField(db_index=True, max_length=128, verbose_name='Filename of downloaded image')),
                ('url', models.URLField(db_index=True, max_length=1024, null=True, verbose_name='URL of image')),
                ('thumb_filename', models.CharField(db_index=True, max_length=128, verbose_name='Filename of downloaded image')),
                ('thumb_url', models.URLField(db_index=True, max_length=1024, null=True, verbose_name='URL of image')),
                ('caption', models.CharField(db_index=True, max_length=1024, null=True, verbose_name='Caption of image')),
                ('meta_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_scraper.metamodel', verbose_name='Link to meta-info')),
                ('scraper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_scraper.scrapermodel', verbose_name='Scraper that retrieved the image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
