# Generated by Django 3.2 on 2021-04-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='thumb_filename',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Filename of downloaded thumbnail image'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='thumb_url',
            field=models.URLField(db_index=True, max_length=1024, null=True, verbose_name='URL of thumbnail image'),
        ),
    ]
