# Generated by Django 3.2 on 2024-09-25 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_scraper', '0003_imageratemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageViewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Create at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Create at')),
                ('user', models.CharField(max_length=32, verbose_name='Username')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_views', to='image_scraper.imagemodel', verbose_name='Viewed image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
