# Generated by Django 3.2 on 2021-04-19 19:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image_scraper', '0002_change_verbose_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Create at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Create at')),
                ('ok', models.BooleanField(verbose_name='Feature processing worked')),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None, verbose_name='CLIP image features')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_features', to='image_scraper.imagemodel', verbose_name='The associated image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
